server:
  port: 8761

eureka:
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  client:
    service_url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
    register-with-eureka: false
    fetch-registry: false
    healthcheck:
      enabled: true

  server:
    enable-self-preservation: false   #自我保护机制，true开启，false关闭
    eviction-interval-timer-in-ms: 60000  #设施检查间隔
